# Generated by Django 4.1.6 on 2023-02-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AR', '0002_registermodel_delete_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='conpassword',
        ),
    ]
