# Generated by Django 4.1.6 on 2023-02-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AR', '0003_remove_registermodel_conpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
