# Generated by Django 4.1.6 on 2023-02-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AR', '0004_loginmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginmodel',
        ),
    ]
