# Generated by Django 4.1.6 on 2023-02-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AR', '0005_delete_loginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
