# Generated by Django 4.1.6 on 2023-02-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AR', '0006_user_registermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_upload_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('imgfile', models.ImageField(upload_to='AR/static/products')),
            ],
        ),
    ]
