# Generated by Django 4.1.6 on 2023-02-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AR', '0008_profile_delete_user_registermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
