# Generated by Django 4.1.6 on 2023-02-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AR', '0009_rename_is_verfied_profile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
