# Generated by Django 4.1.6 on 2023-02-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AR', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='imgfile',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
