# Generated by Django 4.1.6 on 2023-02-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AR', '0012_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('imgfile', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customercard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.IntegerField()),
                ('cardexpiry', models.IntegerField()),
                ('code', models.IntegerField()),
            ],
        ),
    ]
